### ISSUE TITLE
[ValueError]Value of a DataFrame is ambiguous

### ISSUE THREAD

**Issue by harshad16** [thoth-station/glyph#53]
**Describe the bug**

Kebechet run failed due to following error: 
```
2020-09-22 10:53:47,599   1 ERROR    kebechet.config:172: An error occurred during run of manager {'configuration': {'maintainers': ['fridex', 'goern', 'pacospace', 'sesheta'], 'assignees': ['sesheta'], 'labels': ['bot'], 'changelog_file': True}} <class 'kebechet.managers.version.version.VersionManager'> for 'thoth-station/metrics-exporter', skipping
Traceback (most recent call last):
  File "/home/user/kebechet/config.py", line 166, in run_url
    instance.run(**manager_configuration)
  File "/home/user/kebechet/managers/version/version.py", line 433, in run
    version_file=changelog_file,
  File "/home/user/kebechet/managers/version/version.py", line 286, in _compute_changelog
    MLModel.by_name(changelog_classifier),
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/thoth/glyph/lib.py", line 158, in generate_log
    predicted_labels = list(df["labels_predicted"].astype(str)) if df else []
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib64/python3.6/site-packages/pandas/core/generic.py", line 1327, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**To Reproduce**
1. Go to `https://console-openshift-console.apps.ocp.prod.psi.redhat.com/k8s/ns/thoth-backend-stage/pods/kebechet-job-753fff9e-1108258497/logs`
2. See error

**Expected behavior**
Kebechet run should be successful. 

**Additional context**
Related-To: https://github.com/thoth-station/metrics-exporter/issues/522

**Comment by fridex** [comment]
Should be fixed by https://github.com/thoth-station/glyph/pull/52, I'll trigger a new release.

**Comment by goern** [comment]
/close

as the PR got merged
